trigger:
  branches:
    include:
      - main  # Specify your branch here

pool:
  name: 'MyAgentPool'  # Use the agent pool you created

steps:
  - powershell: |
      # Install Composer (if not already installed)
      if (-not (Test-Path "C:\Tools\Composer\composer.phar")) {
          $env:COMPOSER_HOME = "C:\Tools\Composer"
          Invoke-WebRequest -Uri https://getcomposer.org/installer -OutFile "composer-setup.php"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
          Move-Item composer.phar C:\Tools\Composer\composer.phar
      }
      # Add Composer to PATH if it's not already
      [System.Environment]::SetEnvironmentVariable("PATH", $env:PATH + ";C:\Tools\Composer", [System.EnvironmentVariableTarget]::Machine)
    displayName: 'Install Composer'

  - powershell: |
      # Install Laravel dependencies using Composer
      composer install --no-interaction --prefer-dist
    displayName: 'Install Composer Dependencies'

  - powershell: |
      # Run Laravel commands (if needed)
      php artisan key:generate
      php artisan migrate --force
    displayName: 'Run Laravel Commands'

  # Publish build artifacts
  - publish: $(Build.ArtifactStagingDirectory)
    artifact: drop
    displayName: 'Publish Build Artifacts'
