trigger:
  branches:
    include:
      - main  # Specify your branch here

pool:
  name: 'windows'  # Use the agent pool you created

steps:
  - powershell: |
      # Install PHP manually
      Invoke-WebRequest -Uri https://windows.php.net/downloads/releases/php-7.4.3-nts-Win32-vc15-x64.zip -OutFile "php.zip"
      Expand-Archive -Path "php.zip" -DestinationPath "C:\PHP"
      Remove-Item "php.zip"  # Clean up the zip file

      # Add PHP to system PATH
      [System.Environment]::SetEnvironmentVariable("PATH", $env:PATH + ";C:\PHP", [System.EnvironmentVariableTarget]::Machine)
    displayName: 'Install PHP Manually'

  - powershell: |
      # Install Composer
      $env:COMPOSER_HOME = "C:\Tools\Composer"
      Invoke-WebRequest -Uri https://getcomposer.org/installer -OutFile "composer-setup.php"
      php composer-setup.php
      php -r "unlink('composer-setup.php');"
      Move-Item composer.phar C:\Tools\Composer\composer.phar
      $env:PATH += ";C:\Tools\Composer"
    displayName: 'Install Composer'

  - powershell: |
      # Install Laravel dependencies
      composer install --no-interaction --prefer-dist
    displayName: 'Install Composer Dependencies'

  - powershell: |
      # Run Laravel commands
      php artisan key:generate
      php artisan migrate --force
    displayName: 'Run Laravel Commands'

  # Publish build artifacts
  - publish: $(Build.ArtifactStagingDirectory)
    artifact: drop
    displayName: 'Publish Build Artifacts'
