trigger:
  branches:
    include:
      - main  # Specify your branch here

pool:
  name: 'windows'  # Use the agent pool you created

steps:
  - powershell: |
      # Install PHP (using Chocolatey)
      choco install php --version=7.4.3 -y
      $env:PATH += ";C:\tools\php"
    displayName: 'Install PHP'

  - powershell: |
      # Install Composer
      $env:COMPOSER_HOME = "C:\Tools\Composer"
      Invoke-WebRequest -Uri https://getcomposer.org/installer -OutFile "composer-setup.php"
      php composer-setup.php
      php -r "unlink('composer-setup.php');"
      Move-Item composer.phar C:\Tools\Composer\composer.phar
      $env:PATH += ";C:\Tools\Composer"
    displayName: 'Install Composer'

  - powershell: |
      # Install Laravel dependencies
      composer install --no-interaction --prefer-dist
    displayName: 'Install Composer Dependencies'

  - powershell: |
      # Run Laravel commands
      php artisan key:generate
      php artisan migrate --force
    displayName: 'Run Laravel Commands'
